<?php
/**
 * The REST map: what every REST route of this plugin is to an AI agent (lane PLUGIN-MCP).
 *
 * GENERATED by wp/bin/mcp-rest-map.py from its curated table and the live route snapshot
 * wp/tests/wp-integration/mcp-routes.json. Edit the table, never this file: the unit suite
 * refuses a copy that differs, a route the table does not name, and a name with no route.
 *
 * @package Zinn\Cache
 */

declare( strict_types = 1 );

namespace Zinn\Cache\Mcp;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Every endpoint: an ability of its own (run through WordPress's REST dispatch by the kit's
 * Rest_Bridge), covered by a hand-written ability, or exempt with the reason.
 */
final class Rest_Map {

	/**
	 * The entries. Called on `wp_abilities_api_init`, when translations are loaded.
	 *
	 * @return array<int, array<string, string>>
	 */
	public static function entries(): array {
		return array(
			array(
				'method'      => 'POST',
				'route'       => '/zinn-cache/v1/purge',
				'name'        => 'zinn-cache/purge',
				'label'       => __( 'Purge the cache', 'zinn-cache' ),
				'description' => __( 'Discards cached pages: everything (all: true), some addresses (urls) or everything tagged (tags). Pages are rebuilt as visitors arrive.', 'zinn-cache' ),
				'edition'     => 'free',
				'capability'  => 'manage_options (the REST route\'s own check)',
			),
		);
	}
}
